local wk = require("which-key")

wk.register({
    { "xcq", "<cmd>:TodoQuickFix<CR>", desc = "Todo QuickFix" },
    { "xf", group = "Telescope" },
    { "xfb", "<cmd>:Telescope buffers<CR>", desc = "Find buffers" },
    { "xff", "<cmd>:Telescope find_files<CR>", desc = "Find files" },
    { "xfg", "<cmd>:Telescope live_grep<CR>", desc = "Live grep" },
    { "xfh", "<cmd>:Telescope help_tags<CR>", desc = "Help tags" },
    { "xl", group = "LSP" },
    { "xlS", "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>", desc = "Workspace Symbols" },
    { "xla", "<cmd>lua vim.lsp.buf.code_action()<cr>", desc = "Code Action" },
    { "xli", "<cmd>LspInfo<cr>", desc = "Info" },
    { "xll", "<cmd>lua vim.lsp.codelens.run()<cr>", desc = "CodeLens Action" },
    { "xlr", "<cmd>lua vim.lsp.buf.rename()<cr>", desc = "Rename" },
    { "xls", "<cmd>Telescope lsp_document_symbols<cr>", desc = "Document Symbols" },
    { "xm", group = "Mason" },
    { "xmo", "<cmd>:Mason<CR>", desc = "Mason" },
    { "xmu", "<cmd>:MasonUpdate<CR>", desc = "Update Mason packages" },
    { "xn", group = "nvim-tree" },
    { "xnc", "<cmd>:NvimTreeClose<CR>", desc = "Close Nvim Tree" },
    { "xnf", "<cmd>:NvimTreeFocus<CR>", desc = "Focus Nvim Tree" },
    { "xno", "<cmd>:NvimTreeOpen<CR>", desc = "Open Nvim Tree" },
    { "xnt", "<cmd>:NvimTreeToggle<CR>", desc = "Toggle Nvim Tree" },
    { "xs", group = "Session" },
    { "xsc", "<cmd>:SClose<CR>", desc = "Close session" },
    { "xss", "<cmd>:SSave<CR>", desc = "Save session" },
    { "xt", group = "Trouble" },
    { "xtq", "<cmd>:TroubleToggle quickfix<CR>", desc = "Quickfix" },
    { "xtt", "<cmd>:TroubleToggle<CR>", desc = "Toggle" },
    { "xwk", "<cmd>:WhichKey<CR>", desc = "Which Key" },
})
