vim.lsp.enable({
    "lua_ls",
    "sourcekit",
    "pyright",
    "ts_ls",
    "rust_analyzer",
    "somesass_ls",
    "gopls",
    "clangd",
    "html",
    "cssls",
    "bashls",
    "jdtls",
    "dartls"
})

require("mini.icons").setup()
require("mini.snippets").setup()
require("mini.completion").setup()
